# Generated by Django 4.2.6 on 2023-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowNumber', models.IntegerField()),
                ('CustomerId', models.IntegerField()),
                ('Surname', models.CharField(max_length=255)),
                ('CreditScore', models.IntegerField()),
                ('Geography', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Tenure', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('NumOfProducts', models.IntegerField()),
                ('HasCrCard', models.IntegerField()),
                ('IsActiveMember', models.IntegerField()),
                ('EstimatedSalary', models.FloatField()),
                ('Exited', models.IntegerField()),
            ],
        ),
    ]
